server:
  port: 8080

spring:
  application:
    name: jwtForProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/jwtTest
    username: user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      springframework: info
      zerock: debug
#      springframework.security: trace
      springframework.security: INFO


org:
  zerock:
    jwt:
      secret: hello1234567890hello1234567890hello1234567890
